### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by franziskuskiefer** [franziskuskiefer/evercrypt-rust#7]

**Comment by aspenluxxxy** [comment]
Could `aarch64-apple-darwin` be supported?

**Comment by franziskuskiefer** [comment]
> Could `aarch64-apple-darwin` be supported?

I filed #26. I'd be happy to support it but I don't have an M1 to test.

**Comment by aspenluxxxy** [comment]
I can test on my M1 Air.

I would've attempted to PR it myself, but well, I don't really know how to do anything more than adding `"aarch64-apple-darwin" => cfg.set_cross_config_flags(vec!["-target", "aarch64-apple-darwin"]),` to build.rs.
